// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbhpdfnzgbwbdlsmxrhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiaHBkZm56Z2J3YmRsc214cmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2MjYxMzksImV4cCI6MjA4ODIwMjEzOX0.iXOCfruMT6ZzqGZ_wEUYyNLTijCIEOk3cLijJJN6NpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});